#!/bin/bash

# v0.1.0

action=$1
flag=$2
shift

if [[ "$action" == "usage" ]]; then
  echo ""
  echo "  Visualize done tasks:"
  echo "    graph"
  echo "      Draws bar graphs visualizing the number of completed task per day."
  echo "      Optional argument (integer): number of days to visualize (default: 7)"
  echo ""
  exit
fi
if [[ "$action" == "graph" ]]; then
  python "$TODO_ACTIONS_DIR"/graph/graph.py "$TODO_FILE" "$DONE_FILE" $flag
fi
